### ISSUE TITLE
80 Column Text Wrap

### ISSUE THREAD

**Issue by JosephTLyons** [Alhadis/Coding-Style#1]
This is not an issue, I just figured I'd just open this here versus continuing to talk in the `file-icons` issue thread (hopefully this doesn't bother you).  I'm really intrigued by your wrapping of text to exactly 80 columns, it looks great, but seems like pure voodoo!  I tried a test of this and found it to be rather difficult.  I feel as if I have to swap words out and make changes that can obscure the meaning of what I'm trying to say in order to achieve the exact count of 80 columns for each line.  I struggled to get 4 lines to come out perfectly.  I realize this is a silly question, but how much time are you spending, per line, to get this to happen?  Seems like it would be constantly challenging.

**Comment by Alhadis** [comment]
There's no short way to answer this, because the time I spend on commit messages has nothing to do with the reasons you're thinking.

Firstly, it's important you understand that this form of word-wrap-wankery is a very abnormal thing to be doing. It's certainly *not* something I'd ever expect or encourage of anybody else... and it's **most definitely** NOT something you should waste your time doing in everyday practice.

Now, I'm able to do this because of some fucked-up quirk in how my brain is wired. Some freak-mix of literary, spatial and visual-kinesthetic intellect give me a "sixth sense" as I type and watch my editor's cursor close in on some arbitrary boundary. I attribute my proclivity for thinking visually to a background in 3D modelling and animation. Now, when you consider I have +10 years' experience in 3D and 2D graphics software, have a typing speed which clocks in around ~150wpm, and an overactive brain with millions of thoughts flying through it every minute... you can probably understand why churning out a permutation of words which snugly fits a region of space on my screen is by no means difficult for me.

What *is* difficult for me is distilling those "millions of thoughts" into something coherent and readable for other people. Not gonna lie here, dude: as far as communication skills go, mine are probably the worst you'll encounter. Too often I lose myself in my thoughts and my keystrokes become a one-to-one mapping with my current thought process. Inevitably, this leads to digression, opinionated diatribes, or just a heap of confusing and redundant crap that becomes very difficult to follow. This is **before** I hit the big green "Comment" button. I still find myself overthinking and revising my responses (which you can see by the presence of `edited` next to almost every single thing I post on GitHub).

Now... GitHub comments are transient, mutable, and often informal. Git commit messages are not. They're very much the opposite - once you've finished writing a commit message, it's pretty much irreversible (within the scope of sane version control, that is). That's why I can (sometimes) spend too long on commit messages. Not because of some pedantic obsession with lining words up (which I make fun of myself for doing so consistently), but because of how much overthinking I'm doing about making my commits clear, concise, and informative for other people.

Try and imagine what this level of overthinking does to me in physical work environments. If a colleague asks me a technical question, at least 10 different ways to answer are suddenly worming their way through my mouth at once. Unless I pause to think, I end up verbalising fragments of unrelated sentences because my brain *really does do that much thinking*.

Sorry for giving you such a long-winded heap of crap to go through. I hate writing about myself because I feel like some self-obsessed jerk who thinks GitHub is some open-source psychotherapist, which is really the only reason I refrain from talking about real-world related crap...

**Comment by Alhadis** [comment]
I've also left this unamended and unabridged, so you can get a better impression of what my posts would look like if I didn't put so much effort toward cutting them down to a sane word length.

Pretty scary, eh?

**Comment by JosephTLyons** [comment]
Absolutely!  There's no way I could do this in everyday situations or even in rare situations, I just gave it a try to see how challenging it would be.  Turns out, it doesn't come naturally easy for me.  Much respect for being about to write paragraphs upon paragraphs with that additional restriction in mind.  Even though most people wouldn't be able to do this, rendering it impractical for them, it is fairly amazing you can do it naturally.  It looks extremely clean as well.

I also have similar issues with communicating the ideas within my mind concisely, but that comes from a combination of dyslexia, social anxiety, and attempts to be a perfectionist when possible, which gets me into more trouble than it helps me out. :)

**Comment by Alhadis** [comment]
Dyslexia. I have a similar condition called [Dyscalculia](https://en.wikipedia.org/wiki/Dyscalculia) which affects my ability to work with numbers or complex arithmetic.The time it's taken me to get my head around particularly math-heavy problems (mainly when trigonometry is needed) has been absurd. I managed to figure out [De-Casteljau's algorithm](https://github.com/Alhadis/De-Casteljau#this-demo) only with the help of an animation:

<img src="https://upload.wikimedia.org/wikipedia/commons/d/db/B%C3%A9zier_3_big.gif" />

Once grokked, I penned a JavaScript function which you can [find here](https://github.com/Alhadis/Utils/blob/0a713dc4275f7b287a11651aec953254a87021d0/lib/math.js#L70-L113).

Pretty important formula, BTW. It forms the basis for all smooth curves and transitions we see on the web today. I always wanted to know how those worked, haha.

**Comment by JosephTLyons** [comment]
I must've missed your last post... interesting.  i've never heard of Dyscalculia, but it makes perfect sense.  My dyslexia interferes with my ability to keep track of numbers and such when doing math-heavy stuff as well, but not sure if its exactly the same as what you experience.

Anyway, I wanted to ask a few more questions, if that is ok.  They aren't necessarily directly about the perfectly wrapped text, but about hard-wrapping lines and such in general and not using a typical word processor.  I'm about to write a paper for one of my computer science classes and I'm thinking I want to write it all in Atom and track changes via Git and have the repo on Github.  I've been considering dumping some of my older academic papers onto Github to show potential employers my writing, but I figure this would take care of that idea and also be good practice.

First, I was curious what tools you use to write like this?  I recently made some additions to the [Rust language book](https://github.com/rust-lang/book) and sort of got my feet a little wet with writing non-code text in Atom.  Using a column count of 80.  I've downloaded a few packages to make this a bit easier, such as [wordcount](https://github.com/OleMchls/atom-wordcount) and [markdown-pdf](https://github.com/travs/markdown-pdf) (which I plan to use for my paper).   Any other good tools you use for this?

Secondly, I notice I tend to run into this issue a bit.  I format a paragraph as I go along, inserting hard wraps when I reach the column guide, but if I need to go back and fix a word or a sentence, I have to reformat the entire paragraph but "pushing" or "pulling" one word at a time down the paragraph.  I don't think that there will be a super awesome workaround to this, but was curious if this ever happens to you and how you tackle it.

I'm really interested in writing a full paper with markdown and through Atom, i'm just a little worried about it tacking on a ton of extra time with editing and such.  Anyway, that was a long post, my apologies.  Thank you for any suggestions you may have.

**Comment by Alhadis** [comment]
> First, I was curious what tools you use to write like this?

None. Unless the column indicator in the status-bar counts (which literally every text-editor has). You need only wrap one line to a specific length to use it as a visual cue (assuming monospaced text).

> I have to reformat the entire paragraph but "pushing" or "pulling" one word at a time down the paragraph was curious if this ever happens to you and how you tackle it.

Sometimes. If I'm consciously doing the line-wrapping thing and a sentence doesn't fit, I erase it, blank it from my memory, and rewrite it after I'm sure the words are gone from my head (I rarely do this unless it's a commit-message, or I'm actually *trying* to show off).

> I'm really interested in writing a full paper with markdown

Honestly, you're better off using a real document language. Seriously, Markdown is the worst thing to happen to documentation. Ever. Its only virtue is, quite literally, readability. That's it.

Markdown was good when it was confined to its intended purpose - formatting e-mails, forum posts, comment-feeds, etc. Social-type stuff people usually won't proof-read, let alone give any thought to marking shit up with spiffy headings and stuff (you old enough to remember BbCode? Yeah, the only sites using that are ones that haven't been updated since 2007...)

Of course, as with every technology that offers a faster, lazier alternative to the norm, people took it too far. They used it to publish hardcover books, essays, portfolios, entire websites, and worst of all, *software manpages*. Markdown is less a "lightweight markup language".than a standardised notation which machines are able to cleanly interpret. There are no semantics, no real structure beyond headings and lists, and woe betide ye if you nest either of each.

**Comment by Alhadis** [comment]
[Here's](https://raw.githubusercontent.com/Alhadis/Harvester/master/README.md) a recent example:

~~~markdown
3. **In your browser's console,**

	1. **Paste the contents of [`harvester.js`][]**  
	This defines the commands you'll use in the next step.
	It might request your permission to display desktop notifications.
	This is used to notify you when a harvest has finished.
	
	2. **Run `harvest(" … ")` to begin a search.**  
	To search for entire filenames instead of extensions, prepend the query with `filename:`:
		~~~js
		harvest("filename:.bashrc");
		~~~

4. **Wait for it to finish.**  
~~~

Have a look at the indentation necessary to achieve a hierarchy between listed paragraphs and inline code snippets. It's bullshit. And, of course, I keep forgetting how many line-breaks are permitted before the CommonMark parser drops back to "normal paragraph" mode, and it's just a total pain-in-the-arse.

I know I'm biased because I'm comfortable writing in the language, but I stick to Roff for document preparation. When I started learning it, I wasn't even aware it was used for anything beyond the scope of manpages (like most of the modern world). As I picked it up, I was amazed by just how much this language could do. Yes, it's hairy as fuck and at the opposite end of the readability scale, but... damn, that writability.

Once you've overcome the initial learning curve, Roff is fun as hell to write. And the `troff` pipeline is painfully underrated: imagine LaTeX, but with no binary formats, and a more flexible, intuitive pipeline. Sad that its syntax is a turn-off for would-be learners. :confused:

#### Obligatory closing tags for expressing an unusual opinion, expressed in various markup languages:
- **HTML:** `</unpopular-opinion>`
- **Roff:** `.di` (Assuming output is diverted)
- **LaTeX:** `\end{rant}` (Assuming a corresponding `\begin{rant}` command)
- **Markdown:** *"looool, trolled u hard!!!"* :le_cancerous_troll_face:

**Comment by Alhadis** [comment]
> (which you can see by the presence of edited next to almost every single thing I post on GitHub).

<img src="https://user-images.githubusercontent.com/2346707/40919087-c8edc982-684b-11e8-96b3-957db11fef87.png" width="417" alt="Figure 1" />

Lol. Awesome. Now you get to see for yourself! 😉
